[package]
name = "cowsay"
version = "0.1.4"
authors = ["Jose Perez <28468662+ThisNekoGuy@users.noreply.github.com>"]

[dependencies]
clap = ">2.19.2"
rand = "~0.6.5"
phf = { version = "0.7.24", features = ["macros"] }
rust-embed = { version = "5.1.0", features = ["interpolate-folder-path"] }
