[package]
name = "rust-cowsay"
version = "0.1.0"
authors = ["Matt Smith <matthew.smith491@gmail.com>"]

[dependencies]
clap = "~2.19.2"
rand = "~0.6.5"
phf = { version = "0.7.24", features = ["macros"] }
rust-embed = { version = "5.1.0", features = ["interpolate-folder-path"] }
